### ISSUE TITLE
gcc 7.3.0 compilation

### ISSUE THREAD

**Issue by vondele** [Disservin/fast-chess#582]
```
src/config/sanitize.cpp: In function 'void fast_chess::config::sanitize(std::vector<fast_chess::EngineConfiguration>&)':
src/config/sanitize.cpp:98:26: error: 'std::filesystem' has not been declared
         auto p    = std::filesystem::path(configs[i].dir) / std::filesystem::path(configs[i].cmd);
                          ^~~~~~~~~~
src/config/sanitize.cpp:98:66: error: 'std::filesystem' has not been declared
         auto p    = std::filesystem::path(configs[i].dir) / std::filesystem::path(configs[i].cmd);
                                                                  ^~~~~~~~~~
src/config/sanitize.cpp:100:19: error: 'std::filesystem' has not been declared
         if (!std::filesystem::exists(path)) {
                   ^~~~~~~~~~
make[1]: *** [Makefile:133: tmp/src/config/sanitize.o] Error 1
```

**Comment by Disservin** [comment]
missing header include.. yikes

**Comment by vondele** [comment]
works with gcc 7.3.0 now
